[package]
name = "yek-wrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
arboard = "3.4"
anyhow = "1.0"
num-format = "0.4.4"
clap = { version = "4.0", features = ["derive"] }